### ISSUE TITLE
Google Fonts lokal hosten & einbinden

### ISSUE THREAD

**Issue by polarbirke** [DerMarabuu/Porsche-Website#3]
https://github.com/DerMarabuu/Porsche-Website/blob/d316de75b6e61ea9196583cc97378a9e55509234/index.html#L11

Es gibt Gerichtsurteile, die entschieden haben, dass diese Art der Einbindung von Google Fonts gegen die Datenschutzgrundverordnung (DSGVO) verstößt und damit rechtswidrig ist ([Quelle](https://www.e-recht24.de/artikel/datenschutz/13052-datenschutz-und-google-fonts.html)).

Du solltest die Dateien bei Google herunterladen, lokal in einen Ordner ablegen, und von dort einbinden. Das ist von Google aus erlaubt und von deutschem Recht aus erforderlich.

**Comment by sebastiankugler** [comment]
Wow, das ist ja erstaunlich kompliziert über Google. 

@DerMarabuu die Anleitung unter https://wiki.selfhtml.org/wiki/HTML/Tutorials/Google-Fonts_selbst_hosten#Fonts_herunterladen zeigt, wie es geht.
