### ISSUE TITLE
HTML-Markup validieren

### ISSUE THREAD

**Issue by sebastiankugler** [DerMarabuu/Porsche-Website#8]
Mir sind ein paar Fehler im HTML aufgefallen. Sowas kann man mit dem HTML Validator des W3C testen (das W3C ist die Organisation, die die Standards des World Wide Web entwickelt): https://validator.w3.org/

Können wir uns gerne auch mal zusammen anschauen. Das Ergebnis ist vielleicht nicht ganz einfach zu verstehen.

**Comment by DerMarabuu** [comment]
Habe jetzt außer den Leerzeichen in den Bild-Namen habe ich soweit alles validiert.

**Comment by sebastiankugler** [comment]
@DerMarabuu cool. Keinerlei Verständnisprobleme oder Fragen?

Der Commit war https://github.com/DerMarabuu/Porsche-Website/commit/4837b66aa96416dac735318b7a077267f21f6648. Den kannst du übrigens nicht nur über einen PR (Pull Request) mit einem Issue verlinken, sondern auch, indem du direkt in der Commit Message "Fixes #xx" schreibst.

Im Commit habe ich gesehen, dass du den Fehler, der mich dazu gebracht hat, dieses Issue zu eröffnen (`<body>` innerhalb von `<table>`) gefunden und behoben hast. Es gibt übrigens auch ein Body-Tag innerhalb einer Tabelle, das den Hauptinhalt der Tabelle markiert: Das ist `<tbody>`. Vielleicht meintest du das? Mehr dazu bei MDN: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/tbody
